[build]
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "backend/functions"

[functions]
  node_bundler = "esbuild"

# Handle Single Page Application Routing (React-Router-DOM fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
